AWSTemplateFormatVersion:  2010-09-09
Description:  Template for Ec2 Incstances.
Parameters:
  InstanceTypeOption:
    Type: CommaDelimitedList
    Default:  t3.micro, m5.2xlarge, m5.xlarge, m5.large, r5.2xlarge, r5.xlarge, r5.large
  TagKey:
    Type:  String
    Default:  Name
  TagValue:
    Type:  String
    Default:  my
  OutputPrefix:
    Type:  String
    Default:  my
Resources:
# EC201 -- Web Server#1
# EC203 -- Web Server#2
# EC203 -- App Server#1
# EC204 -- App Server#2


Outputs:
