AWSTemplateFormatVersion:  2010-09-09
Description: 3 tier infra template.
#---------------------------------#
# Parameters Section
#---------------------------------#
Parameters:
  AvailabilityZoneOption:
    Type:  CommaDelimitedList
    Default:  ap-northeast-1c, ap-northeast-1a, ap-northeast-1d
  TagValuePrefix:
    Type:  String
    Default:  my
  Tagkey:
    Type:  String
    Default:  Name
  

#---------------------------------#
# Resources Section
#---------------------------------#
Resources:
# VPC
  Vpc:
    Type:  AWS::EC2::VPC
    Properties:  
      CidrBlock:  10.0.0.0/16
      EnableDnsHostnames:  true
      EnableDnsSupport:  true
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-vpc

# Subnet
## Subnet 01
  Subnet01:
    Type:  AWS::EC2::VPC
    Properties: 
      VpcId:  !Ref  Vpc
      AvailabilityZone:  !Select  [  0,  !Ref  AvailabilityZoneOption  ]
      CidrBlock:  10.0.0.0/24
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-Subnet01


# RouteTable
## RouteTable 01
# RouteTable Association
# RouteTable Association 01
# NACL
## NACL 01


#---------------------------------#
# Outputs Section
#---------------------------------#