AWSTemplateFormatVersion:  2010-09-09
Description: 3 tier infra template.
Parameters:
  TagValuePrefix:
    Type:  String
    Default:  my
  Tagkey:
    Type:  String
    Default:  Name
  

#---------------------------------#
# Resources Section
#---------------------------------#
Resources:
  Vpc:
    Type:  AWS::EC2::VPC
    Properties:  
      CidrBlock:  10.0.0.0/16
      EnableDnsHostnames:  true
      EnableDnsSupport:  true
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-vpc


