AWSTemplateFormatVersion:  2010-09-09
Description: 3 tier infra template.
#---------------------------------#
# Parameters Section
#---------------------------------#
Parameters:
  AvailabilityZoneOption:
    Type:  CommaDelimitedList
    Default:  ap-northeast-1c, ap-northeast-1a, ap-northeast-
  CidrBlockVpc:
    Type:  String
    Default:  10.0.0.0/16
  Subnet01CidrBlock:
    Type:  String
    Default:  10.0.0.0/24
  TagValuePrefix:
    Type:  String
    Default:  my
  Tagkey:
    Type:  String
    Default:  Name
  

#---------------------------------#
# Resources Section
#---------------------------------#
Resources:
# VPC
  Vpc:
    Type:  AWS::EC2::VPC
    Properties:  
      CidrBlock:  !Ref  CidrBlockVpc
      EnableDnsHostnames:  true
      EnableDnsSupport:  true
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-vpc

# Subnets
## Subnet 01
  Subnet01:
    Type:  AWS::EC2::VPC
    Properties: 
      VpcId:  !Ref  Vpc
      AvailabilityZone:  !Select  [  0,  !Ref  AvailabilityZoneOption  ]
      CidrBlock:  !Ref  Subnet01CidrBlock
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-Subnet01


# RouteTables
## RouteTable 01
  RouteTable01:
    Type:  AWS::EC2::RouteTable
    Properties:
      VpcId:  !Ref Vpc
      Tags:
        Name:  !Ref  Tagkey
        Value:  !Ref  ${TagValuePrefix}-rtb01
# RouteTable Route
# RouteTable Route 01

# RouteTable Associations
# RouteTable Association 01
# NACLs
## NACL 01
# NACL Associations
## NACL Associations 01



#---------------------------------#
# Outputs Section
#---------------------------------#