AWSTemplateFormatVersion:  2010-09-09
Description: 3 tier infra template.
#---------------------------------#
# Parameters Section
#---------------------------------#
Parameters:
  AvailabilityZoneOption:
    Type:  CommaDelimitedList
    Default:  ap-northeast-1c, ap-northeast-1a, ap-northeast-
  CidrBlockVpc:
    Type:  String
    Default:  10.0.0.0/16
  PublicSubnetDestinationCidrBlock:
    Type:  String
    Default:  0.0.0.0/0
  Subnet01CidrBlock:
    Type:  String
    Default:  10.0.0.0/24
  TagValuePrefix:
    Type:  String
    Default:  my
  Tagkey:
    Type:  String
    Default:  Name
  OutputPrefix:
    Type:  String
    Default:  my
  

#---------------------------------#
# Resources Section
#---------------------------------#
Resources:
# VPC
  Vpc:
    Type:  AWS::EC2::VPC
    Properties:  
      CidrBlock:  !Ref  CidrBlockVpc
      EnableDnsHostnames:  true
      EnableDnsSupport:  true
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-vpc
# Internet Gateway
  Igw01:
    Type:  AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Ref  ${TagValuePrefix}-igw01
# Subnets
## Subnet 01
  Subnet01:
    Type:  AWS::EC2::VPC
    Properties: 
      VpcId:  !Ref  Vpc
      AvailabilityZone:  !Select  [  0,  !Ref  AvailabilityZoneOption  ]
      CidrBlock:  !Ref  Subnet01CidrBlock
      Tags:
        - Key:  !Ref  Tagkey
          Value:  !Sub  ${TagValuePrefix}-Subnet01


# RouteTables
## RouteTable 01
  RouteTable01:
    Type:  AWS::EC2::RouteTable
    Properties:
      VpcId:  !Ref Vpc
      Tags:
        Name:  !Ref  Tagkey
        Value:  !Ref  ${TagValuePrefix}-rtb01

# RouteTable Route
# RouteTable Route 01
  RouteTableRoute01:
    Type:  AWS::EC2::Route
    Properties:
      RouteTableId:  !Ref  RouteTable01
      DestinationCidrBlock:  !Ref  PublicSubnetDestinationCidrBlock
      GatewayId:  !Ref Igw01

# RouteTable Associations
# RouteTable Association 01
  RouteTableAssociation01:
    Type:  AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:  !Ref  Subnet01
      RouteTableId:  !Ref  RouteTable01

# NACLs
## NACL 01
  Nacl01:
    Type:  AWS::EC2::NaclAcl
    Properties:
    VpcId:  !Ref  Vpc
    Tags:
      - Key:  !Ref  Tagkey
        Value:  !Sub  ${TagValuePrefix}-Nacl01

# NACL Entry
  NaclInbound01:
    Type:  AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:  !Ref  Nacl01
      RuleNumber:  32760
      Protocol:  -1
      RuleAction:  allow
      CidrBlock:  0.0.0.0/0
  NaclOutbound01:
    Type:  AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:  !Ref  Nacl01
      Egress:  true
      RuleNumber:  32760
      Protocol:  -1
      RuleAction:  allow
      CidrBlock:  0.0.0.0/0

# NACL Associations
## NACL Associations 01
  NaclAssociation01:
    Type:  AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:  !Ref  Subnet01
      NetworkAclId:  !Ref  Nacl01



#---------------------------------#
# Outputs Section
#---------------------------------#
Outputs:
  VpcIdOutput:
    Value:  !Ref  Vpc
    Export:
      Name:  !Sub  ${OutputPrefix}-Vpc
  Subnet01Output:
    Value:  !Ref Subnet01
    Export:
      Name:  !Sub  ${OutputPrefix}-Subnet01